export const allDatas = {
    data (){
        return {
            allMalls:[
                {
                    areaCode: "110101",
                    areaName: "东城区",
                    brandApproveFlag: false,
                    buildings: null,
                    cityCode: "110100",
                    cityName: "北京市",
                    contractApproveFlag: false,
                    contractFromEnterFlag: false,
                    createBy: "system",
                    createTime: "2019-07-05 15:26:56",
                    deleteFlag: false,
                    fileList: null,
                    groupId: 573,
                    id: 251,
                    mallAddr: "4435554",
                    mallCode: "1521",
                    mallConstructionArea: null,
                    mallFullName: "iris商场",
                    mallLogoUrl: null,
                    mallOpenEndTime: "null",
                    mallOpenStartTime: "null",
                    mallRentArea: null,
                    mallSimpleName: "",
                    mallStartDate: "2019-10-01",
                    mallStatus: 1,
                    mallTel: "",
                    mallType: null,
                    modifyBy: "jingjing",
                    modifyTime: "2019-10-24 18:35:35",
                    oaMallCode: null,
                    provinceCode: "110000",
                    provinceName: "北京市",
                    regionCode: "1520",
                    regionName: "晶晶",
                    remark: null,
                }
            ],
            couponDataLists:[
                {
                    size: 20,
                    total: 1539,
                    list:[
                       {
                        approveLogVoList: null,
                        auditStatus: 4,
                        auditStatusDesc: "审核通过",
                        batchAddFlag: false,
                        cappingPrice: null,
                        chargedOffAmount: 0,
                        couponAvailableTime: null,
                        couponAvailableTimeDescn: null,
                        couponDesc: "33",
                        couponFromChannel: 1,
                        couponGrantWay: 1,
                        couponGrantWayDesc: "营销活动",
                        couponKind: 1,
                        couponKindDesc: "普通券",
                        couponMallShopAssumeVoList: null,
                        couponName: "营销券02",
                        couponOverlayRule: 1,
                        couponOverlayRuleDesc: "不可叠加",
                        couponSubTitle: null,
                        couponType: 1,
                        couponTypeDesc: "现金券",
                        couponUploadRecordId: null,
                        couponUrl: null,
                        couponWorth: 11,
                        createBy: "100000",
                        createTime: "2019-12-11 14:24:43",
                        dedicatedShopVoList: [],
                        deleteFlag: false,
                        discount: null,
                        effectEdUpdateFlag: false,
                        fileAttachmentVoList: null,
                        groupFlag: false,
                        id: 2844,
                        integralAmount: null,
                        integralShopDisplayFlag: false,
                        lastModifyName: null,
                        mainCouponFlag: null,
                        mallVoList: [{mallCode: "1537", mallName: "晶晶商场2哈哈哈哈哈"}],
                        maxAcquirableAmount: 33,
                        modifyBy: "100000",
                        modifyFrom: 1,
                        modifyTime: "2019-12-11 14:25:06",
                        needActivateFlag: false,
                        parentId: null,
                        purchaseChannel: null,
                        purchaseChannelDesc: null,
                        purchaseRuleVoList: [],
                        purchaseWay: null,
                        purchaseWayDesc: null,
                        remark: null,
                        shopDedicatedFlag: true,
                        soldAmount: 0,
                        subVoList: null,
                        thresholdPrice: null,
                        totalAmount: 34,
                        transferFlag: false,
                        usableAmount: 21,
                        useRuleDesc: "33",
                        userName: null,
                       }
                   ]
                }
            ]
        }
    }
}